name = "Simplicity of Vanilla"
author = "pajic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4b6676a980435bf5ff55fb404bc4269caf0859de16bda36419f91cc2db58885"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.6", "1.21"]
