name = "Simplicity of Vanilla"
author = "pajic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f884dc536a149441792610db164fe982d099dbb9406d1e53c57b7f54473acacd"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
