name = "Simplicity of Vanilla"
author = "pajic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc62cd3a28f0ba698a898d2382bc15ad661e7e8bfcbb840f62506d39af2846f9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.6", "1.21"]
datapack-folder = "datapacks"
