name = "Simplicity of Vanilla"
author = "pajic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25dd9c02c4598fa84b2dff23686816ff0bf07ee91a8d527a0dfe7a5c1802a59a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.6", "1.21"]
datapack-folder = "datapacks"
